spring.application.name=HospitalManagementSystem

server.servlet.context-path=/api/v1

    

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/HospitalManagementSystem
spring.datasource.username=postgres
spring.datasource.password=Udi<3#Shrao
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false


spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

# security config
#spring.security.user.name=Shrao
#spring.security.user.password=pass

jwt.secretKey=jbkuy34g5o723tgout3yg23ygrt3187y0874hr3oufg2087gf4orugb4ujyegfo378