spring.application.name=SpringJDBC-example
spring.datasource.url=jdbc:postgresql://localhost:5432/Student
spring.datasource.username=postgres
spring.datasource.password=Udi<3#Shrao
spring.datasource.driver-class-name=org.postgresql.Driver
