spring.application.name=miniaws

server.servlet.context-path=/api/v1

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/miniaws
spring.datasource.username=postgres
spring.datasource.password=Udi<3#Shrao
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

file.upload-dir=C:\\JavaDev_endgame\\Projects\\miniaws\\miniaws_localStorage

jwt.secretKey=al4J4t/kVPlonLruF78fzD6JhzkZl7zl7PYuLpMwMqM=

